# Generated by Django 3.2.7 on 2021-09-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('kakao', models.CharField(max_length=30, null=True)),
                ('naver', models.CharField(max_length=30, null=True)),
                ('image', models.URLField(max_length=2000, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('namecard', models.TextField(max_length=3000, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
