# Generated by Django 3.2.7 on 2021-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210914_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
