# Generated by Django 3.2.7 on 2021-09-16 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210914_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='end_year',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='history',
            name='start_year',
        ),
    ]
