# Generated by Django 3.2.7 on 2021-09-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210916_0551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='namecard',
            new_name='introduce',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='slogan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
