# Generated by Django 3.2.7 on 2021-10-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211014_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
