# Generated by Django 3.2.7 on 2021-09-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='view_count',
        ),
        migrations.CreateModel(
            name='Viewcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.posting')),
            ],
            options={
                'db_table': 'viewcounts',
            },
        ),
    ]
